# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'development-resources/Qt UI/UI2018.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("eTree Browser")
        MainWindow.resize(1345, 750)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("centralwidget {\n"
"  background-color: #DBDBDB;\n"
"}\n"
"QMainWindow { background-color: #f4f4f4 }\n"
"\n"
"QPushButton {\n"
"  background-color: #FFFFFF;\n"
"  color: #242424;\n"
"}\n"
"\n"
"QComboBox {\n"
"  background-color: #FFFFFF;\n"
"  color: #242424;\n"
"}\n"
"\n"
"\n"
"QTabWidget {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #f4f4f4, stop: 1 #FFFFFF);            \n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    padding: 7px;\n"
"    border: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"    background-color: #f4f4f4;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridTrackInfo = QtWidgets.QGridLayout()
        self.gridTrackInfo.setObjectName("gridTrackInfo")
        self.playbackControlsVLayout = QtWidgets.QVBoxLayout()
        self.playbackControlsVLayout.setObjectName("playbackControlsVLayout")
        self.playbackBehaviourLayout = QtWidgets.QGridLayout()
        self.playbackBehaviourLayout.setObjectName("playbackBehaviourLayout")
        self.repeatCombo = QtWidgets.QComboBox(self.centralwidget)
        self.repeatCombo.setStyleSheet("")
        self.repeatCombo.setObjectName("repeatCombo")
        self.repeatCombo.addItem("")
        self.repeatCombo.addItem("")
        self.repeatCombo.addItem("")
        self.playbackBehaviourLayout.addWidget(self.repeatCombo, 0, 0, 1, 1)
        self.lastfmBtn = QtWidgets.QPushButton(self.centralwidget)
        self.lastfmBtn.setStyleSheet("")
        self.lastfmBtn.setText("")
        self.lastfmBtn.setObjectName("lastfmBtn")
        self.playbackBehaviourLayout.addWidget(self.lastfmBtn, 0, 1, 1, 1)
        self.playbackControlsVLayout.addLayout(self.playbackBehaviourLayout)
        self.playbackControlsLayout = QtWidgets.QGridLayout()
        self.playbackControlsLayout.setObjectName("playbackControlsLayout")
        self.playPauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playPauseBtn.setStyleSheet("")
        self.playPauseBtn.setText("")
        self.playPauseBtn.setObjectName("playPauseBtn")
        self.playbackControlsLayout.addWidget(self.playPauseBtn, 0, 1, 1, 1)
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setStyleSheet("")
        self.prevBtn.setText("")
        self.prevBtn.setObjectName("prevBtn")
        self.playbackControlsLayout.addWidget(self.prevBtn, 0, 0, 1, 1)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setStyleSheet("")
        self.nextBtn.setText("")
        self.nextBtn.setObjectName("nextBtn")
        self.playbackControlsLayout.addWidget(self.nextBtn, 0, 2, 1, 1)
        self.playbackControlsVLayout.addLayout(self.playbackControlsLayout)
        self.gridTrackInfo.addLayout(self.playbackControlsVLayout, 0, 0, 1, 1)
        self.audioPositionLayout = QtWidgets.QVBoxLayout()
        self.audioPositionLayout.setObjectName("audioPositionLayout")
        self.trackLbl = QtWidgets.QLabel(self.centralwidget)
        self.trackLbl.setText("")
        self.trackLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.trackLbl.setObjectName("trackLbl")
        self.audioPositionLayout.addWidget(self.trackLbl)
        self.timeLbl = QtWidgets.QLabel(self.centralwidget)
        self.timeLbl.setText("")
        self.timeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLbl.setObjectName("timeLbl")
        self.audioPositionLayout.addWidget(self.timeLbl)
        self.trackProgress = QtWidgets.QSlider(self.centralwidget)
        self.trackProgress.setOrientation(QtCore.Qt.Horizontal)
        self.trackProgress.setObjectName("trackProgress")
        self.audioPositionLayout.addWidget(self.trackProgress)
        self.gridTrackInfo.addLayout(self.audioPositionLayout, 0, 1, 1, 1)
        self.volumeLayout = QtWidgets.QVBoxLayout()
        self.volumeLayout.setObjectName("volumeLayout")
        self.volumeLbl = QtWidgets.QLabel(self.centralwidget)
        self.volumeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.volumeLbl.setObjectName("volumeLbl")
        self.volumeLayout.addWidget(self.volumeLbl)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setStyleSheet("")
        self.volumeSlider.setPageStep(5)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeLayout.addWidget(self.volumeSlider)
        self.gridTrackInfo.addLayout(self.volumeLayout, 0, 2, 1, 1)
        self.gridTrackInfo.setColumnStretch(0, 20)
        self.gridTrackInfo.setColumnStretch(1, 60)
        self.gridTrackInfo.setColumnStretch(2, 20)
        self.verticalLayout_2.addLayout(self.gridTrackInfo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topMenuTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.topMenuTabs.setStyleSheet("")
        self.topMenuTabs.setObjectName("topMenuTabs")
        self.nowPlayingTab = QtWidgets.QWidget()
        self.nowPlayingTab.setStyleSheet("")
        self.nowPlayingTab.setObjectName("nowPlayingTab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.nowPlayingTab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.historyTopLayoutBoxes = QtWidgets.QHBoxLayout()
        self.historyTopLayoutBoxes.setObjectName("historyTopLayoutBoxes")
        self.nowPlayingLayout = QtWidgets.QVBoxLayout()
        self.nowPlayingLayout.setObjectName("nowPlayingLayout")
        self.nowPlayingLbl = QtWidgets.QLabel(self.nowPlayingTab)
        self.nowPlayingLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nowPlayingLbl.setObjectName("nowPlayingLbl")
        self.nowPlayingLayout.addWidget(self.nowPlayingLbl)
        self.playlist_view = QtWidgets.QListView(self.nowPlayingTab)
        self.playlist_view.setObjectName("playlist_view")
        self.nowPlayingLayout.addWidget(self.playlist_view)
        self.historyTopLayoutBoxes.addLayout(self.nowPlayingLayout)
        self.similarArtistLayout = QtWidgets.QVBoxLayout()
        self.similarArtistLayout.setObjectName("similarArtistLayout")
        self.similarArtistLbl = QtWidgets.QLabel(self.nowPlayingTab)
        self.similarArtistLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.similarArtistLbl.setObjectName("similarArtistLbl")
        self.similarArtistLayout.addWidget(self.similarArtistLbl)
        self.similarArtistsList = QtWidgets.QListWidget(self.nowPlayingTab)
        self.similarArtistsList.setObjectName("similarArtistsList")
        self.similarArtistLayout.addWidget(self.similarArtistsList)
        self.historyTopLayoutBoxes.addLayout(self.similarArtistLayout)
        self.lastFMLayout = QtWidgets.QVBoxLayout()
        self.lastFMLayout.setObjectName("lastFMLayout")
        self.mostPlayedReleasesLbl_2 = QtWidgets.QLabel(self.nowPlayingTab)
        self.mostPlayedReleasesLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mostPlayedReleasesLbl_2.setObjectName("mostPlayedReleasesLbl_2")
        self.lastFMLayout.addWidget(self.mostPlayedReleasesLbl_2)
        self.artistTagsList = QtWidgets.QListWidget(self.nowPlayingTab)
        self.artistTagsList.setObjectName("artistTagsList")
        self.lastFMLayout.addWidget(self.artistTagsList)
        self.historyTopLayoutBoxes.addLayout(self.lastFMLayout)
        self.verticalLayout_15.addLayout(self.historyTopLayoutBoxes)
        spacerItem = QtWidgets.QSpacerItem(40, 350, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem)
        self.topMenuTabs.addTab(self.nowPlayingTab, "")
        self.browseTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseTab.sizePolicy().hasHeightForWidth())
        self.browseTab.setSizePolicy(sizePolicy)
        self.browseTab.setStyleSheet("")
        self.browseTab.setObjectName("browseTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.browseTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.browseTabUpperHLayout = QtWidgets.QHBoxLayout()
        self.browseTabUpperHLayout.setSpacing(0)
        self.browseTabUpperHLayout.setObjectName("browseTabUpperHLayout")
        self.browseTabHLayout = QtWidgets.QHBoxLayout()
        self.browseTabHLayout.setSpacing(0)
        self.browseTabHLayout.setObjectName("browseTabHLayout")
        self.browseCriteriaVLayout = QtWidgets.QVBoxLayout()
        self.browseCriteriaVLayout.setSpacing(0)
        self.browseCriteriaVLayout.setObjectName("browseCriteriaVLayout")
        self.browseCriteriaLayout = QtWidgets.QHBoxLayout()
        self.browseCriteriaLayout.setSpacing(0)
        self.browseCriteriaLayout.setObjectName("browseCriteriaLayout")
        self.typeOrderByCombo = QtWidgets.QComboBox(self.browseTab)
        self.typeOrderByCombo.setStyleSheet("")
        self.typeOrderByCombo.setObjectName("typeOrderByCombo")
        self.typeOrderByCombo.addItem("")
        self.typeOrderByCombo.addItem("")
        self.browseCriteriaLayout.addWidget(self.typeOrderByCombo)
        self.typeBrowseCombo = QtWidgets.QComboBox(self.browseTab)
        self.typeBrowseCombo.setStyleSheet("")
        self.typeBrowseCombo.setObjectName("typeBrowseCombo")
        self.typeBrowseCombo.addItem("")
        self.typeBrowseCombo.addItem("")
        self.typeBrowseCombo.addItem("")
        self.browseCriteriaLayout.addWidget(self.typeBrowseCombo)
        self.browseCriteriaLayout.setStretch(0, 1)
        self.browseCriteriaLayout.setStretch(1, 13)
        self.browseCriteriaVLayout.addLayout(self.browseCriteriaLayout)
        self.browseTagsLayout = QtWidgets.QVBoxLayout()
        self.browseTagsLayout.setSpacing(0)
        self.browseTagsLayout.setObjectName("browseTagsLayout")
        self.quickFilter = QtWidgets.QLineEdit(self.browseTab)
        self.quickFilter.setObjectName("quickFilter")
        self.browseTagsLayout.addWidget(self.quickFilter)
        self.browseList = QtWidgets.QListView(self.browseTab)
        self.browseList.setStyleSheet("")
        self.browseList.setObjectName("browseList")
        self.browseTagsLayout.addWidget(self.browseList)
        self.browseCriteriaVLayout.addLayout(self.browseTagsLayout)
        self.browseTabHLayout.addLayout(self.browseCriteriaVLayout)
        self.performanceViewLayout = QtWidgets.QVBoxLayout()
        self.performanceViewLayout.setSpacing(0)
        self.performanceViewLayout.setObjectName("performanceViewLayout")
        self.treeViewFilter = QtWidgets.QLineEdit(self.browseTab)
        self.treeViewFilter.setObjectName("treeViewFilter")
        self.performanceViewLayout.addWidget(self.treeViewFilter)
        self.browseTreeView = QtWidgets.QTreeView(self.browseTab)
        self.browseTreeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.browseTreeView.setObjectName("browseTreeView")
        self.browseTreeView.header().setMinimumSectionSize(40)
        self.performanceViewLayout.addWidget(self.browseTreeView)
        self.browseTabHLayout.addLayout(self.performanceViewLayout)
        self.browseTabHLayout.setStretch(0, 20)
        self.browseTabHLayout.setStretch(1, 80)
        self.browseTabUpperHLayout.addLayout(self.browseTabHLayout)
        self.additionalInfoFrame = QtWidgets.QWidget(self.browseTab)
        self.additionalInfoFrame.setObjectName("additionalInfoFrame")
        self.browseTabUpperHLayout.addWidget(self.additionalInfoFrame)
        self.browseTabUpperHLayout.setStretch(0, 6)
        self.browseTabUpperHLayout.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.browseTabUpperHLayout)
        self.topMenuTabs.addTab(self.browseTab, "")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setStyleSheet("")
        self.searchTab.setObjectName("searchTab")
        self.topMenuTabs.addTab(self.searchTab, "")
        self.historyTab = QtWidgets.QWidget()
        self.historyTab.setObjectName("historyTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.historyTab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.historyVLayout = QtWidgets.QVBoxLayout()
        self.historyVLayout.setObjectName("historyVLayout")
        self.historyTopLayout = QtWidgets.QHBoxLayout()
        self.historyTopLayout.setObjectName("historyTopLayout")
        self.savedSearchedLayout = QtWidgets.QVBoxLayout()
        self.savedSearchedLayout.setObjectName("savedSearchedLayout")
        self.savedSearchesLabel = QtWidgets.QLabel(self.historyTab)
        self.savedSearchesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.savedSearchesLabel.setObjectName("savedSearchesLabel")
        self.savedSearchedLayout.addWidget(self.savedSearchesLabel)
        self.savedSearchesList = QtWidgets.QListWidget(self.historyTab)
        self.savedSearchesList.setObjectName("savedSearchesList")
        self.savedSearchedLayout.addWidget(self.savedSearchesList)
        self.historyTopLayout.addLayout(self.savedSearchedLayout)
        self.mostPlayedArtistLayout = QtWidgets.QVBoxLayout()
        self.mostPlayedArtistLayout.setObjectName("mostPlayedArtistLayout")
        self.mostPlayedArtistsLbl = QtWidgets.QLabel(self.historyTab)
        self.mostPlayedArtistsLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mostPlayedArtistsLbl.setObjectName("mostPlayedArtistsLbl")
        self.mostPlayedArtistLayout.addWidget(self.mostPlayedArtistsLbl)
        self.mostPlayedArtistsTbl = QtWidgets.QListWidget(self.historyTab)
        self.mostPlayedArtistsTbl.setObjectName("mostPlayedArtistsTbl")
        self.mostPlayedArtistLayout.addWidget(self.mostPlayedArtistsTbl)
        self.historyTopLayout.addLayout(self.mostPlayedArtistLayout)
        self.mostPlayedLayout = QtWidgets.QVBoxLayout()
        self.mostPlayedLayout.setObjectName("mostPlayedLayout")
        self.mostPlayedReleasesLbl = QtWidgets.QLabel(self.historyTab)
        self.mostPlayedReleasesLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mostPlayedReleasesLbl.setObjectName("mostPlayedReleasesLbl")
        self.mostPlayedLayout.addWidget(self.mostPlayedReleasesLbl)
        self.mostPlayedReleasesTbl = QtWidgets.QListWidget(self.historyTab)
        self.mostPlayedReleasesTbl.setObjectName("mostPlayedReleasesTbl")
        self.mostPlayedLayout.addWidget(self.mostPlayedReleasesTbl)
        self.historyTopLayout.addLayout(self.mostPlayedLayout)
        self.historyVLayout.addLayout(self.historyTopLayout)
        self.playbackHistoryLabel = QtWidgets.QLabel(self.historyTab)
        self.playbackHistoryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playbackHistoryLabel.setObjectName("playbackHistoryLabel")
        self.historyVLayout.addWidget(self.playbackHistoryLabel)
        self.historyTableWidget = QtWidgets.QTableWidget(self.historyTab)
        self.historyTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.historyTableWidget.setObjectName("historyTableWidget")
        self.historyTableWidget.setColumnCount(0)
        self.historyTableWidget.setRowCount(0)
        self.historyVLayout.addWidget(self.historyTableWidget)
        self.historyVLayout.setStretch(0, 2)
        self.historyVLayout.setStretch(2, 5)
        self.verticalLayout_14.addLayout(self.historyVLayout)
        self.topMenuTabs.addTab(self.historyTab, "")
        self.PreferencesTab = QtWidgets.QWidget()
        self.PreferencesTab.setObjectName("PreferencesTab")
        self.tabWidget = QtWidgets.QTabWidget(self.PreferencesTab)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1141, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.prefApplicationTab = QtWidgets.QWidget()
        self.prefApplicationTab.setObjectName("prefApplicationTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.prefApplicationTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.prefApplicationVLayout = QtWidgets.QVBoxLayout()
        self.prefApplicationVLayout.setSpacing(1)
        self.prefApplicationVLayout.setObjectName("prefApplicationVLayout")
        self.prefApplicationHLayout = QtWidgets.QHBoxLayout()
        self.prefApplicationHLayout.setObjectName("prefApplicationHLayout")
        self.preferredFormatLabel = QtWidgets.QLabel(self.prefApplicationTab)
        self.preferredFormatLabel.setObjectName("preferredFormatLabel")
        self.prefApplicationHLayout.addWidget(self.preferredFormatLabel)
        self.preferredFormatCombo = QtWidgets.QComboBox(self.prefApplicationTab)
        self.preferredFormatCombo.setObjectName("preferredFormatCombo")
        self.preferredFormatCombo.addItem("")
        self.preferredFormatCombo.addItem("")
        self.preferredFormatCombo.addItem("")
        self.preferredFormatCombo.addItem("")
        self.preferredFormatCombo.addItem("")
        self.prefApplicationHLayout.addWidget(self.preferredFormatCombo)
        self.prefApplicationHLayout.setStretch(1, 2)
        self.prefApplicationVLayout.addLayout(self.prefApplicationHLayout)
        self.outputDeviceLayout = QtWidgets.QHBoxLayout()
        self.outputDeviceLayout.setObjectName("outputDeviceLayout")
        self.audioOutputLbl = QtWidgets.QLabel(self.prefApplicationTab)
        self.audioOutputLbl.setObjectName("audioOutputLbl")
        self.outputDeviceLayout.addWidget(self.audioOutputLbl)
        self.audioOutputCombo = QtWidgets.QComboBox(self.prefApplicationTab)
        self.audioOutputCombo.setObjectName("audioOutputCombo")
        self.outputDeviceLayout.addWidget(self.audioOutputCombo)
        self.outputDeviceLayout.setStretch(1, 2)
        self.prefApplicationVLayout.addLayout(self.outputDeviceLayout)
        self.historyonLoadChk = QtWidgets.QCheckBox(self.prefApplicationTab)
        self.historyonLoadChk.setChecked(True)
        self.historyonLoadChk.setObjectName("historyonLoadChk")
        self.prefApplicationVLayout.addWidget(self.historyonLoadChk)
        self.debugChk = QtWidgets.QCheckBox(self.prefApplicationTab)
        self.debugChk.setChecked(False)
        self.debugChk.setObjectName("debugChk")
        self.prefApplicationVLayout.addWidget(self.debugChk)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.prefApplicationVLayout.addItem(spacerItem1)
        self.prefApplicationVLayout.setStretch(3, 1)
        self.prefApplicationVLayout.setStretch(4, 4)
        self.horizontalLayout_7.addLayout(self.prefApplicationVLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(3, 5)
        self.tabWidget.addTab(self.prefApplicationTab, "")
        self.prefLastFMTab = QtWidgets.QWidget()
        self.prefLastFMTab.setObjectName("prefLastFMTab")
        self.lastfmStatus = QtWidgets.QPushButton(self.prefLastFMTab)
        self.lastfmStatus.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.lastfmStatus.setText("")
        self.lastfmStatus.setObjectName("lastfmStatus")
        self.tabWidget.addTab(self.prefLastFMTab, "")
        self.topMenuTabs.addTab(self.PreferencesTab, "")
        self.verticalLayout.addWidget(self.topMenuTabs)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.topMenuTabs.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eTree Browser"))
        self.repeatCombo.setItemText(0, _translate("MainWindow", "Repeat All"))
        self.repeatCombo.setItemText(1, _translate("MainWindow", "Repeat Current"))
        self.repeatCombo.setItemText(2, _translate("MainWindow", "Shuffle"))
        self.volumeLbl.setText(_translate("MainWindow", "Volume"))
        self.nowPlayingLbl.setText(_translate("MainWindow", "Playlist (Now Playing)"))
        self.similarArtistLbl.setText(_translate("MainWindow", "Similar Artists to Now Playing"))
        self.mostPlayedReleasesLbl_2.setText(_translate("MainWindow", " Last.FM Tags"))
        self.topMenuTabs.setTabText(self.topMenuTabs.indexOf(self.nowPlayingTab), _translate("MainWindow", "Now Playing"))
        self.typeOrderByCombo.setItemText(0, _translate("MainWindow", "Asc"))
        self.typeOrderByCombo.setItemText(1, _translate("MainWindow", "Desc"))
        self.typeBrowseCombo.setItemText(0, _translate("MainWindow", "Artist"))
        self.typeBrowseCombo.setItemText(1, _translate("MainWindow", "Genre"))
        self.typeBrowseCombo.setItemText(2, _translate("MainWindow", "Location"))
        self.quickFilter.setPlaceholderText(_translate("MainWindow", "Filter browse tags"))
        self.treeViewFilter.setPlaceholderText(_translate("MainWindow", "Filter performances"))
        self.topMenuTabs.setTabText(self.topMenuTabs.indexOf(self.browseTab), _translate("MainWindow", "Browse"))
        self.topMenuTabs.setTabText(self.topMenuTabs.indexOf(self.searchTab), _translate("MainWindow", "Search"))
        self.savedSearchesLabel.setText(_translate("MainWindow", "Saved Searches"))
        self.mostPlayedArtistsLbl.setText(_translate("MainWindow", "Most Played Artists"))
        self.mostPlayedReleasesLbl.setText(_translate("MainWindow", "Most Played Releases"))
        self.playbackHistoryLabel.setText(_translate("MainWindow", "Playback History"))
        self.topMenuTabs.setTabText(self.topMenuTabs.indexOf(self.historyTab), _translate("MainWindow", "History"))
        self.preferredFormatLabel.setText(_translate("MainWindow", "Preferred Format:"))
        self.preferredFormatCombo.setItemText(0, _translate("MainWindow", "MP3 (64Kbps)"))
        self.preferredFormatCombo.setItemText(1, _translate("MainWindow", "MP3 (VBR)"))
        self.preferredFormatCombo.setItemText(2, _translate("MainWindow", "FLAC"))
        self.preferredFormatCombo.setItemText(3, _translate("MainWindow", "OGG"))
        self.preferredFormatCombo.setItemText(4, _translate("MainWindow", "SHN"))
        self.audioOutputLbl.setText(_translate("MainWindow", "Output Device:"))
        self.historyonLoadChk.setText(_translate("MainWindow", "Search For \"On This Day\" On Load"))
        self.debugChk.setText(_translate("MainWindow", "Show Debug Interface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prefApplicationTab), _translate("MainWindow", "Application"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prefLastFMTab), _translate("MainWindow", "Last.FM"))
        self.topMenuTabs.setTabText(self.topMenuTabs.indexOf(self.PreferencesTab), _translate("MainWindow", "Preferences"))

